# Generated by Django 3.2.25 on 2024-05-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_orderlineitem_metal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='metal_type',
        ),
    ]
