# Generated by Django 3.2.25 on 2024-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
