# Generated by Django 3.2.25 on 2024-05-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_metal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='metal_type',
        ),
    ]
